@startuml
left to right direction
skinparam actorStyle awesome

:Administrateur: as Admin

rectangle Application {
  Admin -- (Gérer les utilisateurs)
  Admin -- (Importer une liste de conteneurs)
  Admin -- (Consulter les rapports d'activité)
  
  (Gérer les utilisateurs) .> (S'authentifier) : <<include>>
  (Importer une liste de conteneurs) .> (S'authentifier) : <<include>>
  (Consulter les rapports d'activité) .> (S'authentifier) : <<include>>
}
@enduml